token: "INSERT YOU DISCORD TOKEN HERE"
channelList: 
   "<DISCORD CHANNEL ID>":
      botToken: "123412345:AABBCCDDEEFFGGHHIIJJKKLLMMNNOOPPQQR"
      telegramChatID: 12345678
   "<DISCORD CHANNEL ID>":
      botToken: "123412345:AABBCCDDEEFFGGHHIIJJKKLLMMNNOOPPQQR"
      telegramChatID: 12345678